"""SQLAlchemy models for the Geomatrix FastAPI backend."""
from datetime import datetime
from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()

class Project(Base):
    __tablename__ = "projects"
    id = Column(String, primary_key=True)
    project_code = Column(String, unique=True, nullable=False)
    name = Column(String, nullable=False)
    state = Column(String, nullable=False)
    district = Column(String, nullable=False)
    authority = Column(String, nullable=False)
    project_type = Column(String, nullable=False)
    description = Column(Text)
    latitude = Column(Float)
    longitude = Column(Float)
    land_required = Column(Float, default=0.0)
    land_acquired = Column(Float, default=0.0)
    affected_families = Column(Integer, default=0)
    current_stage = Column(String)
    status = Column(String)
    validation_status = Column(String, default="pending")
    data_classification = Column(String, default="REAL")
    source_name = Column(String)
    source_url = Column(String)
    source_record_id = Column(String)
    imported_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    compensation_status = Column(String)
    objection_count = Column(Integer, default=0)
    legal_case_count = Column(Integer, default=0)
    rr_status = Column(String)
    env_clearance_status = Column(String)
    forest_clearance_status = Column(String)
    crz_status = Column(String)
    doc_completeness_pct = Column(Float, nullable=True)
    approval_pending = Column(Boolean, default=False)
    overdue_milestones = Column(Integer, default=0)
    risk_score = Column(Float)
    risk_level = Column(String)
    delay_probability = Column(Float)
    predicted_delay_days = Column(Integer)
    confidence = Column(Float)
    primary_driver = Column(String)
    alerts = relationship("Alert", back_populates="project", cascade="all, delete-orphan")
    predictions = relationship("RiskPrediction", back_populates="project", cascade="all, delete-orphan")

class HistoricalDelayRecord(Base):
    __tablename__ = "historical_delay_records"
    id = Column(String, primary_key=True)
    project_code = Column(String)
    state = Column(String)
    project_type = Column(String)
    land_area_ha = Column(Float)
    affected_families = Column(Integer)
    pending_claims = Column(Integer)
    legal_cases = Column(Integer)
    doc_completeness_pct = Column(Float)
    approval_pending = Column(Boolean)
    rr_pending = Column(Integer)
    overdue_milestones = Column(Integer)
    actual_delay_days = Column(Integer, nullable=True)
    delayed = Column(Boolean, nullable=False)
    validation_status = Column(String, default="pending")
    data_classification = Column(String, default="REAL")
    source_name = Column(String)
    source_url = Column(String)
    source_record_id = Column(String)
    imported_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ModelRun(Base):
    __tablename__ = "model_runs"
    id = Column(String, primary_key=True)
    algorithm = Column(String)
    trained_at = Column(DateTime, default=datetime.utcnow)
    n_samples = Column(Integer)
    n_features = Column(Integer)
    feature_names = Column(JSON)
    precision = Column(Float)
    recall = Column(Float)
    f1_score = Column(Float)
    roc_auc = Column(Float)
    rmse = Column(Float)
    accuracy = Column(Float)
    model_path = Column(String)
    model_version = Column(String)
    is_active = Column(Boolean, default=True)
    notes = Column(Text)

class GeminiInsight(Base):
    __tablename__ = "gemini_insights"
    id = Column(String, primary_key=True)
    project_id = Column(String, ForeignKey("projects.id"), nullable=False)
    model_run_id = Column(String, ForeignKey("model_runs.id"))
    summary = Column(Text)
    recommendations = Column(JSON)
    generated_at = Column(DateTime, default=datetime.utcnow)

class RiskPrediction(Base):
    __tablename__ = "risk_predictions"
    id = Column(String, primary_key=True)
    project_id = Column(String, ForeignKey("projects.id"), nullable=False)
    model_run_id = Column(String, ForeignKey("model_runs.id"))
    risk_score = Column(Float)
    risk_level = Column(String)
    delay_probability = Column(Float)
    predicted_delay_days = Column(Integer, nullable=True)
    confidence = Column(Float, nullable=True)
    shap_values = Column(JSON)
    predicted_at = Column(DateTime, default=datetime.utcnow)
    project = relationship("Project", back_populates="predictions")

class Alert(Base):
    __tablename__ = "alerts"
    id = Column(String, primary_key=True)
    project_id = Column(String, ForeignKey("projects.id"), nullable=False)
    severity = Column(String)
    reason = Column(Text)
    detected_at = Column(DateTime, default=datetime.utcnow)
    recommended_action = Column(Text)
    status = Column(String, default="Open")
    project = relationship("Project", back_populates="alerts")

class DataIngestionLog(Base):
    __tablename__ = "data_ingestion_log"
    id = Column(String, primary_key=True)
    source = Column(String)
    source_name = Column(String)
    source_url = Column(String)
    started_at = Column(DateTime, default=datetime.utcnow)
    triggered_at = Column(DateTime, default=datetime.utcnow)
    finished_at = Column(DateTime)
    records_fetched = Column(Integer, default=0)
    records_saved = Column(Integer, default=0)
    records_skipped = Column(Integer, default=0)
    errors = Column(JSON)
    error_message = Column(Text)
    status = Column(String, default="running")

class AuditLog(Base):
    __tablename__ = "audit_logs"
    id = Column(String, primary_key=True)
    actor_email = Column(String, nullable=True, index=True)
    action = Column(String, nullable=False)
    entity_type = Column(String, nullable=False)
    entity_id = Column(String, nullable=False)
    previous_value = Column(JSON, nullable=True)
    new_value = Column(JSON, nullable=True)
    request_id = Column(String, nullable=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
